UI menu.c32
PROMPT 0

MENU TITLE MixUpOS Boot menu
TIMEOUT 10
DEFAULT MixUpOS

LABEL MixUpOS
    MENU LABEL MixUpOS
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 --- ../Kernel

LABEL MixUpOSText
    MENU LABEL MixUpOS (text mode)
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 graphics_subsystem_mode=off --- ../Kernel

LABEL MixUpOSNoACPI
    MENU LABEL MixUpOS (No ACPI)
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 acpi=off --- ../Kernel

LABEL MixUpOSSerialDebug
    MENU LABEL MixUpOS (with serial debug)
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 serial_debug --- ../Kernel
